// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"github.com/panupakm/boutique-go/app/checkout/internal/biz"
	"github.com/panupakm/boutique-go/app/checkout/internal/conf"
	"github.com/panupakm/boutique-go/app/checkout/internal/data"
	"github.com/panupakm/boutique-go/app/checkout/internal/server"
	"github.com/panupakm/boutique-go/app/checkout/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	cartServiceClient := data.NewCartServiceClient(confData)
	catalogClient := data.NewCatalogServiceClient(confData)
	userClient := data.NewUserServiceClient(confData)
	dataData, cleanup, err := data.NewData(cartServiceClient, catalogClient, userClient, logger)
	if err != nil {
		return nil, nil, err
	}
	cartRepo := data.NewCartRepo(dataData, logger)
	cartUseCase := biz.NewCartUseCase(cartRepo, logger)
	catalogRepo := data.NewCatalogRepo(dataData, logger)
	catalogUseCase := biz.NewCatalogUseCase(catalogRepo, logger)
	userRepo := data.NewUserRepo(dataData, logger)
	userUseCase := biz.NewUserUseCase(userRepo, logger)
	checkoutUseCase := biz.NewCheckoutUseCase(cartUseCase, catalogUseCase, userUseCase, logger)
	checkoutService := service.NewCheckoutService(checkoutUseCase, logger)
	grpcServer := server.NewGRPCServer(confServer, checkoutService, logger)
	httpServer := server.NewHTTPServer(confServer, checkoutService, logger)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
