// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/panupakm/boutique-go/app/user/internal/data/ent/card"
	"github.com/panupakm/boutique-go/app/user/internal/data/ent/predicate"
	"github.com/panupakm/boutique-go/app/user/internal/data/ent/user"
)

// CardUpdate is the builder for updating Card entities.
type CardUpdate struct {
	config
	hooks    []Hook
	mutation *CardMutation
}

// Where appends a list predicates to the CardUpdate builder.
func (cu *CardUpdate) Where(ps ...predicate.Card) *CardUpdate {
	cu.mutation.Where(ps...)
	return cu
}

// SetNumber sets the "number" field.
func (cu *CardUpdate) SetNumber(s string) *CardUpdate {
	cu.mutation.SetNumber(s)
	return cu
}

// SetName sets the "name" field.
func (cu *CardUpdate) SetName(s string) *CardUpdate {
	cu.mutation.SetName(s)
	return cu
}

// SetCcv sets the "ccv" field.
func (cu *CardUpdate) SetCcv(i int) *CardUpdate {
	cu.mutation.ResetCcv()
	cu.mutation.SetCcv(i)
	return cu
}

// AddCcv adds i to the "ccv" field.
func (cu *CardUpdate) AddCcv(i int) *CardUpdate {
	cu.mutation.AddCcv(i)
	return cu
}

// SetExpirationYear sets the "expiration_year" field.
func (cu *CardUpdate) SetExpirationYear(i int) *CardUpdate {
	cu.mutation.ResetExpirationYear()
	cu.mutation.SetExpirationYear(i)
	return cu
}

// AddExpirationYear adds i to the "expiration_year" field.
func (cu *CardUpdate) AddExpirationYear(i int) *CardUpdate {
	cu.mutation.AddExpirationYear(i)
	return cu
}

// SetExpirationMonth sets the "expiration_month" field.
func (cu *CardUpdate) SetExpirationMonth(i int) *CardUpdate {
	cu.mutation.ResetExpirationMonth()
	cu.mutation.SetExpirationMonth(i)
	return cu
}

// AddExpirationMonth adds i to the "expiration_month" field.
func (cu *CardUpdate) AddExpirationMonth(i int) *CardUpdate {
	cu.mutation.AddExpirationMonth(i)
	return cu
}

// SetOwnerID sets the "owner" edge to the User entity by ID.
func (cu *CardUpdate) SetOwnerID(id uuid.UUID) *CardUpdate {
	cu.mutation.SetOwnerID(id)
	return cu
}

// SetNillableOwnerID sets the "owner" edge to the User entity by ID if the given value is not nil.
func (cu *CardUpdate) SetNillableOwnerID(id *uuid.UUID) *CardUpdate {
	if id != nil {
		cu = cu.SetOwnerID(*id)
	}
	return cu
}

// SetOwner sets the "owner" edge to the User entity.
func (cu *CardUpdate) SetOwner(u *User) *CardUpdate {
	return cu.SetOwnerID(u.ID)
}

// Mutation returns the CardMutation object of the builder.
func (cu *CardUpdate) Mutation() *CardMutation {
	return cu.mutation
}

// ClearOwner clears the "owner" edge to the User entity.
func (cu *CardUpdate) ClearOwner() *CardUpdate {
	cu.mutation.ClearOwner()
	return cu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (cu *CardUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, cu.sqlSave, cu.mutation, cu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (cu *CardUpdate) SaveX(ctx context.Context) int {
	affected, err := cu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (cu *CardUpdate) Exec(ctx context.Context) error {
	_, err := cu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cu *CardUpdate) ExecX(ctx context.Context) {
	if err := cu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (cu *CardUpdate) check() error {
	if v, ok := cu.mutation.Number(); ok {
		if err := card.NumberValidator(v); err != nil {
			return &ValidationError{Name: "number", err: fmt.Errorf(`ent: validator failed for field "Card.number": %w`, err)}
		}
	}
	if v, ok := cu.mutation.Name(); ok {
		if err := card.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Card.name": %w`, err)}
		}
	}
	if v, ok := cu.mutation.Ccv(); ok {
		if err := card.CcvValidator(v); err != nil {
			return &ValidationError{Name: "ccv", err: fmt.Errorf(`ent: validator failed for field "Card.ccv": %w`, err)}
		}
	}
	if v, ok := cu.mutation.ExpirationYear(); ok {
		if err := card.ExpirationYearValidator(v); err != nil {
			return &ValidationError{Name: "expiration_year", err: fmt.Errorf(`ent: validator failed for field "Card.expiration_year": %w`, err)}
		}
	}
	if v, ok := cu.mutation.ExpirationMonth(); ok {
		if err := card.ExpirationMonthValidator(v); err != nil {
			return &ValidationError{Name: "expiration_month", err: fmt.Errorf(`ent: validator failed for field "Card.expiration_month": %w`, err)}
		}
	}
	return nil
}

func (cu *CardUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := cu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(card.Table, card.Columns, sqlgraph.NewFieldSpec(card.FieldID, field.TypeUUID))
	if ps := cu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := cu.mutation.Number(); ok {
		_spec.SetField(card.FieldNumber, field.TypeString, value)
	}
	if value, ok := cu.mutation.Name(); ok {
		_spec.SetField(card.FieldName, field.TypeString, value)
	}
	if value, ok := cu.mutation.Ccv(); ok {
		_spec.SetField(card.FieldCcv, field.TypeInt, value)
	}
	if value, ok := cu.mutation.AddedCcv(); ok {
		_spec.AddField(card.FieldCcv, field.TypeInt, value)
	}
	if value, ok := cu.mutation.ExpirationYear(); ok {
		_spec.SetField(card.FieldExpirationYear, field.TypeInt, value)
	}
	if value, ok := cu.mutation.AddedExpirationYear(); ok {
		_spec.AddField(card.FieldExpirationYear, field.TypeInt, value)
	}
	if value, ok := cu.mutation.ExpirationMonth(); ok {
		_spec.SetField(card.FieldExpirationMonth, field.TypeInt, value)
	}
	if value, ok := cu.mutation.AddedExpirationMonth(); ok {
		_spec.AddField(card.FieldExpirationMonth, field.TypeInt, value)
	}
	if cu.mutation.OwnerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   card.OwnerTable,
			Columns: []string{card.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cu.mutation.OwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   card.OwnerTable,
			Columns: []string{card.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, cu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{card.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	cu.mutation.done = true
	return n, nil
}

// CardUpdateOne is the builder for updating a single Card entity.
type CardUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *CardMutation
}

// SetNumber sets the "number" field.
func (cuo *CardUpdateOne) SetNumber(s string) *CardUpdateOne {
	cuo.mutation.SetNumber(s)
	return cuo
}

// SetName sets the "name" field.
func (cuo *CardUpdateOne) SetName(s string) *CardUpdateOne {
	cuo.mutation.SetName(s)
	return cuo
}

// SetCcv sets the "ccv" field.
func (cuo *CardUpdateOne) SetCcv(i int) *CardUpdateOne {
	cuo.mutation.ResetCcv()
	cuo.mutation.SetCcv(i)
	return cuo
}

// AddCcv adds i to the "ccv" field.
func (cuo *CardUpdateOne) AddCcv(i int) *CardUpdateOne {
	cuo.mutation.AddCcv(i)
	return cuo
}

// SetExpirationYear sets the "expiration_year" field.
func (cuo *CardUpdateOne) SetExpirationYear(i int) *CardUpdateOne {
	cuo.mutation.ResetExpirationYear()
	cuo.mutation.SetExpirationYear(i)
	return cuo
}

// AddExpirationYear adds i to the "expiration_year" field.
func (cuo *CardUpdateOne) AddExpirationYear(i int) *CardUpdateOne {
	cuo.mutation.AddExpirationYear(i)
	return cuo
}

// SetExpirationMonth sets the "expiration_month" field.
func (cuo *CardUpdateOne) SetExpirationMonth(i int) *CardUpdateOne {
	cuo.mutation.ResetExpirationMonth()
	cuo.mutation.SetExpirationMonth(i)
	return cuo
}

// AddExpirationMonth adds i to the "expiration_month" field.
func (cuo *CardUpdateOne) AddExpirationMonth(i int) *CardUpdateOne {
	cuo.mutation.AddExpirationMonth(i)
	return cuo
}

// SetOwnerID sets the "owner" edge to the User entity by ID.
func (cuo *CardUpdateOne) SetOwnerID(id uuid.UUID) *CardUpdateOne {
	cuo.mutation.SetOwnerID(id)
	return cuo
}

// SetNillableOwnerID sets the "owner" edge to the User entity by ID if the given value is not nil.
func (cuo *CardUpdateOne) SetNillableOwnerID(id *uuid.UUID) *CardUpdateOne {
	if id != nil {
		cuo = cuo.SetOwnerID(*id)
	}
	return cuo
}

// SetOwner sets the "owner" edge to the User entity.
func (cuo *CardUpdateOne) SetOwner(u *User) *CardUpdateOne {
	return cuo.SetOwnerID(u.ID)
}

// Mutation returns the CardMutation object of the builder.
func (cuo *CardUpdateOne) Mutation() *CardMutation {
	return cuo.mutation
}

// ClearOwner clears the "owner" edge to the User entity.
func (cuo *CardUpdateOne) ClearOwner() *CardUpdateOne {
	cuo.mutation.ClearOwner()
	return cuo
}

// Where appends a list predicates to the CardUpdate builder.
func (cuo *CardUpdateOne) Where(ps ...predicate.Card) *CardUpdateOne {
	cuo.mutation.Where(ps...)
	return cuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (cuo *CardUpdateOne) Select(field string, fields ...string) *CardUpdateOne {
	cuo.fields = append([]string{field}, fields...)
	return cuo
}

// Save executes the query and returns the updated Card entity.
func (cuo *CardUpdateOne) Save(ctx context.Context) (*Card, error) {
	return withHooks(ctx, cuo.sqlSave, cuo.mutation, cuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (cuo *CardUpdateOne) SaveX(ctx context.Context) *Card {
	node, err := cuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (cuo *CardUpdateOne) Exec(ctx context.Context) error {
	_, err := cuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cuo *CardUpdateOne) ExecX(ctx context.Context) {
	if err := cuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (cuo *CardUpdateOne) check() error {
	if v, ok := cuo.mutation.Number(); ok {
		if err := card.NumberValidator(v); err != nil {
			return &ValidationError{Name: "number", err: fmt.Errorf(`ent: validator failed for field "Card.number": %w`, err)}
		}
	}
	if v, ok := cuo.mutation.Name(); ok {
		if err := card.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Card.name": %w`, err)}
		}
	}
	if v, ok := cuo.mutation.Ccv(); ok {
		if err := card.CcvValidator(v); err != nil {
			return &ValidationError{Name: "ccv", err: fmt.Errorf(`ent: validator failed for field "Card.ccv": %w`, err)}
		}
	}
	if v, ok := cuo.mutation.ExpirationYear(); ok {
		if err := card.ExpirationYearValidator(v); err != nil {
			return &ValidationError{Name: "expiration_year", err: fmt.Errorf(`ent: validator failed for field "Card.expiration_year": %w`, err)}
		}
	}
	if v, ok := cuo.mutation.ExpirationMonth(); ok {
		if err := card.ExpirationMonthValidator(v); err != nil {
			return &ValidationError{Name: "expiration_month", err: fmt.Errorf(`ent: validator failed for field "Card.expiration_month": %w`, err)}
		}
	}
	return nil
}

func (cuo *CardUpdateOne) sqlSave(ctx context.Context) (_node *Card, err error) {
	if err := cuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(card.Table, card.Columns, sqlgraph.NewFieldSpec(card.FieldID, field.TypeUUID))
	id, ok := cuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Card.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := cuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, card.FieldID)
		for _, f := range fields {
			if !card.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != card.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := cuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := cuo.mutation.Number(); ok {
		_spec.SetField(card.FieldNumber, field.TypeString, value)
	}
	if value, ok := cuo.mutation.Name(); ok {
		_spec.SetField(card.FieldName, field.TypeString, value)
	}
	if value, ok := cuo.mutation.Ccv(); ok {
		_spec.SetField(card.FieldCcv, field.TypeInt, value)
	}
	if value, ok := cuo.mutation.AddedCcv(); ok {
		_spec.AddField(card.FieldCcv, field.TypeInt, value)
	}
	if value, ok := cuo.mutation.ExpirationYear(); ok {
		_spec.SetField(card.FieldExpirationYear, field.TypeInt, value)
	}
	if value, ok := cuo.mutation.AddedExpirationYear(); ok {
		_spec.AddField(card.FieldExpirationYear, field.TypeInt, value)
	}
	if value, ok := cuo.mutation.ExpirationMonth(); ok {
		_spec.SetField(card.FieldExpirationMonth, field.TypeInt, value)
	}
	if value, ok := cuo.mutation.AddedExpirationMonth(); ok {
		_spec.AddField(card.FieldExpirationMonth, field.TypeInt, value)
	}
	if cuo.mutation.OwnerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   card.OwnerTable,
			Columns: []string{card.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cuo.mutation.OwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   card.OwnerTable,
			Columns: []string{card.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Card{config: cuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, cuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{card.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	cuo.mutation.done = true
	return _node, nil
}
