// Code generated by protoc-gen-go-errors. DO NOT EDIT.

package email

import (
	fmt "fmt"
	errors "github.com/go-kratos/kratos/v2/errors"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
const _ = errors.SupportPackageIsVersion1

func IsUnknownError(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == EmailServiceErrorReason_UNKNOWN_ERROR.String() && e.Code == 500
}

func ErrorUnknownError(format string, args ...interface{}) *errors.Error {
	return errors.New(500, EmailServiceErrorReason_UNKNOWN_ERROR.String(), fmt.Sprintf(format, args...))
}

func IsConnectionLost(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == EmailServiceErrorReason_CONNECTION_LOST.String() && e.Code == 500
}

func ErrorConnectionLost(format string, args ...interface{}) *errors.Error {
	return errors.New(500, EmailServiceErrorReason_CONNECTION_LOST.String(), fmt.Sprintf(format, args...))
}
