// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.23.3
// source: email/email_error.proto

package email

import (
	_ "github.com/go-kratos/kratos/v2/errors"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EmailServiceErrorReason int32

const (
	EmailServiceErrorReason_UNKNOWN_ERROR   EmailServiceErrorReason = 0
	EmailServiceErrorReason_CONNECTION_LOST EmailServiceErrorReason = 1
)

// Enum value maps for EmailServiceErrorReason.
var (
	EmailServiceErrorReason_name = map[int32]string{
		0: "UNKNOWN_ERROR",
		1: "CONNECTION_LOST",
	}
	EmailServiceErrorReason_value = map[string]int32{
		"UNKNOWN_ERROR":   0,
		"CONNECTION_LOST": 1,
	}
)

func (x EmailServiceErrorReason) Enum() *EmailServiceErrorReason {
	p := new(EmailServiceErrorReason)
	*p = x
	return p
}

func (x EmailServiceErrorReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EmailServiceErrorReason) Descriptor() protoreflect.EnumDescriptor {
	return file_email_email_error_proto_enumTypes[0].Descriptor()
}

func (EmailServiceErrorReason) Type() protoreflect.EnumType {
	return &file_email_email_error_proto_enumTypes[0]
}

func (x EmailServiceErrorReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EmailServiceErrorReason.Descriptor instead.
func (EmailServiceErrorReason) EnumDescriptor() ([]byte, []int) {
	return file_email_email_error_proto_rawDescGZIP(), []int{0}
}

var File_email_email_error_proto protoreflect.FileDescriptor

var file_email_email_error_proto_rawDesc = []byte{
	0x0a, 0x17, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x2f, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x5f, 0x65, 0x72,
	0x72, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x61, 0x70, 0x69, 0x2e, 0x65,
	0x6d, 0x61, 0x69, 0x6c, 0x1a, 0x13, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x73, 0x2f, 0x65, 0x72, 0x72,
	0x6f, 0x72, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2a, 0x47, 0x0a, 0x17, 0x45, 0x6d, 0x61,
	0x69, 0x6c, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x65,
	0x61, 0x73, 0x6f, 0x6e, 0x12, 0x11, 0x0a, 0x0d, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x5f,
	0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0x00, 0x12, 0x13, 0x0a, 0x0f, 0x43, 0x4f, 0x4e, 0x4e, 0x45,
	0x43, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x4c, 0x4f, 0x53, 0x54, 0x10, 0x01, 0x1a, 0x04, 0xa0, 0x45,
	0xf4, 0x03, 0x42, 0x3e, 0x0a, 0x09, 0x61, 0x70, 0x69, 0x2e, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x50,
	0x01, 0x5a, 0x2f, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x70, 0x61,
	0x6e, 0x75, 0x70, 0x61, 0x6b, 0x6d, 0x2f, 0x62, 0x6f, 0x75, 0x74, 0x69, 0x71, 0x75, 0x65, 0x2d,
	0x67, 0x6f, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x3b, 0x65, 0x6d, 0x61,
	0x69, 0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_email_email_error_proto_rawDescOnce sync.Once
	file_email_email_error_proto_rawDescData = file_email_email_error_proto_rawDesc
)

func file_email_email_error_proto_rawDescGZIP() []byte {
	file_email_email_error_proto_rawDescOnce.Do(func() {
		file_email_email_error_proto_rawDescData = protoimpl.X.CompressGZIP(file_email_email_error_proto_rawDescData)
	})
	return file_email_email_error_proto_rawDescData
}

var file_email_email_error_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_email_email_error_proto_goTypes = []interface{}{
	(EmailServiceErrorReason)(0), // 0: api.email.EmailServiceErrorReason
}
var file_email_email_error_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_email_email_error_proto_init() }
func file_email_email_error_proto_init() {
	if File_email_email_error_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_email_email_error_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_email_email_error_proto_goTypes,
		DependencyIndexes: file_email_email_error_proto_depIdxs,
		EnumInfos:         file_email_email_error_proto_enumTypes,
	}.Build()
	File_email_email_error_proto = out.File
	file_email_email_error_proto_rawDesc = nil
	file_email_email_error_proto_goTypes = nil
	file_email_email_error_proto_depIdxs = nil
}
