version: '3'
services:
  # mailhog:
  #   image: mailhog/mailhog:latest
  #   ports:
  #     - 8025:8025
  #     - 1025:1025
  # redis:
  #   image: redis:latest
  #   ports:
  #     - 6379:6379
  mongo:
    image: mongo:4.4
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: catalog
      MONGO_INITDB_USERNAME: user
      MONGO_INITDB_PASSWORD: password
    ports:
      - "27017:27017"
    volumes:
      - ./init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh
