version: '3'
services:
  # mailhog:
  #   image: mailhog/mailhog:latest
  #   ports:
  #     - 8025:8025
  #     - 1025:1025
  redis:
    image: redis:latest
    ports:
      - 6379:6379
  # jaeger:
  #   image: jaegertracing/all-in-one:1.49
  #   environment:
  #     - COLLECTOR_ZIPKIN_HOST_PORT=:9411
  #   ports:
  #     - 6831:6831/udp
  #     - 6832:6832/udp
  #     - 5778:5778
  #     - 16686:16686
  #     - 4317:4317
  #     - 4318:4318
  #     - 14250:14250
  #     - 14268:14268
  #     - 14269:14269
  #     - 9411:9411